[Variables]

;--- Sizes
ButtonSize  = 30
LineSize    = 2

;--- Colors
LineColor   = 234, 253, 259, 230
GlitchColor = 62, 230, 107

NoColor= 0,0,0,0
White= 255, 255, 255, 250
Black= 0, 0, 0, 180

;--- Margins
Margin= 30

;--- Image settings
Path        = #@#/Img/
Font= Roboto

;--- Text styles
[Base]
AntiAlias= 1
FontFace= Roboto
FontColor= #White#

[Title]
FontSize= 15

[Simple]
FontSize= 10

[TSTL]
AntiAlias= 1
FontFace= Roboto
StringAlign= LeftCenter
FontColor= 255,255,255,200
FontSize= 8
clipString = 1
